# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/express-v4
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/fastify-v5
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/koa-v3
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /libs/eslint-config-altair
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-api-utils
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-api
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-app
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-core
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-crx
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-db
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-docs
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-electron-interop
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-electron-settings-static
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-electron-settings
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-electron
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-express-middleware
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-fastify-plugin
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-iframe-sandbox
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-koa-middleware
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-plugin
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-static
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-tauri-isolation
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/altair-tauri
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/gatsby-plugin-altair-graphql
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/login-redirect
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/transactional
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /plugins/ai
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /plugins/apollo-tracing
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /test-server
    schedule:
      interval: daily
