packages:
  - 'apps/**'
  - 'packages/**'
  - 'libs/**'
  - 'plugins/**'
  # if required, exclude some directories
  # - '!**/test/**'

catalog:
  '@types/node': 25.5.0
  electron: ^39.8.5
  typescript: ^5.8.0
  vite: ^7.3.2
  '@vitest/coverage-v8': ^4.1.0
  vitest: ^4.1.0
  zod: ^4.1.13

minimumReleaseAge: 1440
trustPolicy: no-downgrade
strictDepBuilds: true
onlyBuiltDependencies: []
ignoredBuiltDependencies: []
