packages:
  - 'apps/**'
  - 'packages/**'
  - 'libs/**'
  - 'plugins/**'
  # if required, exclude some directories
  # - '!**/test/**'

catalog:
  electron: ^38.3.0
  typescript: ^5.8.0
  zod: ^4.1.13
  vite: ^7.3.0
  vitest: ^3.0.5

minimumReleaseAge: 1440
trustPolicy: no-downgrade
strictDepBuilds: true
onlyBuiltDependencies: []
ignoredBuiltDependencies: []
