# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Altair GraphQL Client"
email: samuelimolo4real@gmail.com
download_link: https://github.com/imolorhe/altair/releases/latest
description: > # this means to ignore newlines until "baseurl:"
  The best GraphQL Client you will ever need
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
releases:
  -
    name: macOS
    image: osx_logo.svg
    unique_term: darwin
    link: https://github.com/imolorhe/altair/releases/latest
  -
    name: linux
    image: linux_logo.svg
    unique_term: deb
    link:
  -
    name: windows
    image: windows_logo.svg
    unique_term: exe
    link:
  -
    name: chrome
    image: chrome_icon.svg
    link: https://chrome.google.com/webstore/detail/altair-graphql-client/flnheeellpciglgpaodhkhmapeljopja
  -
    name: firefox
    image: firefox_logo.svg
    link: https://addons.mozilla.org/en-US/firefox/addon/altair-graphql-client/

ex:
  -
    name: web
    image: webapp_icon.svg
    link: https://altair-gql.herokuapp.com/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
