# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Altair GraphQL Client
short_title: Altair GraphQL
logo_url: /assets/img/altair.svg
email: altair@sirmuel.design
download_link: https://github.com/imolorhe/altair/releases/latest
description: > # this means to ignore newlines until "baseurl:"
  A beautiful feature-rich GraphQL Client IDE for all platforms. Available for MacOS, Windows, Linux, Chrome, Firefox.
  Enables you interact with any GraphQL server you are authorized to access from any platform you are on.
  Much like Postman for GraphQL, you can easily test and optimize your GraphQL implementations.
  You also have several features to make your GraphQL development process much easier including subscriptions,
  query scaffolding, formatting, multiple languages, themes, and many more.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
seo_image: /assets/img/app-shot.png
seo_author: Samuel Imolorhe
releases:
  -
    name: macOS
    image: osx_logo.svg
    unique_term: dmg
    link: https://github.com/imolorhe/altair/releases/latest
    extra: brew install --cask altair-graphql-client
  -
    name: macOS M1
    image: osx_logo.svg
    unique_term: _arm64_mac.dmg
  -
    name: linux
    image: linux_logo.svg
    unique_term: AppImage
    link:
    extra: snap install altair
  -
    name: windows
    image: windows_logo.svg
    unique_term: exe
    link:
    extra: choco install altair-graphql
  -
    name: chrome
    image: chrome_icon.svg
    link: https://chrome.google.com/webstore/detail/altair-graphql-client/flnheeellpciglgpaodhkhmapeljopja
  -
    name: firefox
    image: firefox_logo.svg
    link: https://addons.mozilla.org/en-US/firefox/addon/altair-graphql-client/
  -
    name: edge
    image: edge_icon.svg
    link: https://microsoftedge.microsoft.com/addons/detail/altair-graphql-client/kpggioiimijgcalmnfnalgglgooonopa
  -
    name: web
    image: webapp_icon.svg
    link: https://altair-gql.sirmuel.design/
learn_more: >
  A beautiful feature-rich GraphQL Client IDE for all platforms. Available for MacOS, Windows, Linux, Chrome, Firefox.
  Enables you interact with any GraphQL server you are authorized to access from any platform you are on.
  Much like Postman for GraphQL, you can easily test and optimize your GraphQL implementations.
  You also have several features to make your GraphQL development process much easier including subscriptions, query scaffolding, formatting, multiple languages, themes, and many more.

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-feed


remote_theme: imolorhe/just-the-docs
# Enable or disable the site search
search_enabled: true
# Aux links for the upper right navigation
aux_links:
  "Altair on GitHub":
    - "https://github.com/imolorhe/altair"
# Color scheme currently only supports "dark" or nil (default)
# color_scheme: 'dark'
# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-41432833-7


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
