name: Firebase deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
  # pull_request: # Temporary dev trigger

env:
  NODE_VERSION: 18
  # NODE_OPTIONS: --openssl-legacy-provider

# TODO: Delete
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn --frozen-lockfile --network-timeout 1000000
      - run: yarn build:ci
      - name: Create Firebase deploy service account key locally
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAIN }}' > $HOME/gcloud.json
      - name: Deploy firebase services
        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && yarn deploy:firebase
