name: API E2E Testing

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:20

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
          POSTGRES_DB: tests
        ports:
          - 5434:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: yarn --frozen-lockfile --network-timeout 1000000
      - name: Build apps (with retries)
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: yarn build:ci
      - name: Update env file
        run: |
          echo DATABASE_URL="postgresql://prisma:prisma@postgres:5434/tests?schema=public" >> packages/altair-api/.env.e2e
          cat packages/altair-api/.env.e2e
      - name: Migration
        run: yarn --cwd packages/altair-api migrate:e2e
      - name: Run E2E
        # Runs a script that creates a PostgreSQL table, populates
        # the table with data, and then retrieves the data.
        run: yarn --cwd packages/altair-api test:e2e
