name: Sites deploy workflow

on:
  workflow_call:
    inputs:
      node_version:
        description: 'Node.js version to use'
        required: true
        type: string
      deploy_docs:
        description: 'Whether to deploy docs'
        required: false
        default: true
        type: boolean
      deploy_redirect:
        description: 'Whether to deploy redirect'
        required: false
        default: true
        type: boolean
      deploy_sandbox:
        description: 'Whether to deploy sandbox'
        required: false
        default: true
        type: boolean

jobs:
  deploy:
    name: Deploy sites
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ inputs.node_version }}
      - run: yarn --frozen-lockfile --network-timeout 1000000
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NODE_OPTIONS: '--max_old_space_size=4096' # Getting Javascript heap out of memory error. Increasing heap size
      # https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/#use-github-actions
      # TODO: Make this reusable
      - run: |
          export CLOUDFLARE_API_TOKEN="${{ secrets.CLOUDFLARE_API_TOKEN }}"
          export CLOUDFLARE_ACCOUNT_ID="${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
          cd packages/altair-docs
          npx wrangler@2 pages publish ".vitepress/dist" --project-name="altair-site"
        if: ${{ inputs.deploy_docs }}
      - run: |
          export CLOUDFLARE_API_TOKEN="${{ secrets.CLOUDFLARE_API_TOKEN }}"
          export CLOUDFLARE_ACCOUNT_ID="${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
          cd packages/login-redirect
          npx wrangler@2 pages publish "dist" --project-name="altair-login-redirect"
        if: ${{ inputs.deploy_redirect }}
      - run: |
          export CLOUDFLARE_API_TOKEN="${{ secrets.CLOUDFLARE_API_TOKEN }}"
          export CLOUDFLARE_ACCOUNT_ID="${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
          cd packages/altair-iframe-sandbox
          npx wrangler@2 pages publish "dist" --project-name="altair-iframe-sandbox"
        if: ${{ inputs.deploy_sandbox }}
